// <auto-generated />
using System;
using BrokerFlow.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable enable

namespace BrokerFlow.Api.Migrations
{
    [DbContext(typeof(BrokerFlowDbContext))]
    partial class BrokerFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrokerFlow.Api.Models.AppConfig", b =>
            {
                b.Property<string>("Key").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("Value").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Key");
                b.ToTable("AppConfigs");
            });

            modelBuilder.Entity("BrokerFlow.Api.Models.AuditEntry", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<string>("Action").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Details").HasColumnType("nvarchar(max)");
                b.Property<string>("EntityId").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("EntityType").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.ToTable("AuditEntries");
            });

            modelBuilder.Entity("BrokerFlow.Api.Models.MappingConfig", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("RulesJson").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<bool>("SplitOutput").HasColumnType("bit");
                b.Property<string>("SplitConditionJson").HasColumnType("nvarchar(max)");
                b.Property<string>("SplitFileNamePattern").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("SourceId").HasColumnType("nvarchar(max)");
                b.Property<string>("TemplateId").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("XmlTemplate").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("MappingConfigs");
            });

            modelBuilder.Entity("BrokerFlow.Api.Models.ProcessingJob", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("ErrorMessage").HasColumnType("nvarchar(max)");
                b.Property<string>("FilePath").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("FilesGenerated").HasColumnType("int");
                b.Property<DateTime?>("FinishedAt").HasColumnType("datetime2");
                b.Property<string>("MappingId").HasColumnType("nvarchar(max)");
                b.Property<string>("OriginalFileName").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("RecordsProcessed").HasColumnType("int");
                b.Property<string>("ResultPath").HasColumnType("nvarchar(max)");
                b.Property<string>("SourceId").HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("StartedAt").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("Status");
                b.ToTable("ProcessingJobs");
            });

            modelBuilder.Entity("BrokerFlow.Api.Models.Schedule", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CronExpression").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("Enabled").HasColumnType("bit");
                b.Property<DateTime?>("LastRunAt").HasColumnType("datetime2");
                b.Property<string>("MappingId").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("NextRunAt").HasColumnType("datetime2");
                b.Property<string>("SourceId").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Schedules");
            });

            modelBuilder.Entity("BrokerFlow.Api.Models.Source", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CsvCustomSeparator").HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("CsvSeparator").HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<bool>("Enabled").HasColumnType("bit");
                b.Property<string>("FileFormat").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("FileMask").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Path").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Name");
                b.ToTable("Sources");
            });

            modelBuilder.Entity("BrokerFlow.Api.Models.XmlTemplate", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<string>("Content").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("FieldsJson").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.ToTable("XmlTemplates");
            });
#pragma warning restore 612, 618
        }
    }
}
